import "./globals.css";
import { Roboto_Mono, IBM_Plex_Sans } from 'next/font/google'



const roboto_mono_init = Roboto_Mono({
  subsets: ['latin'],
  weight: ["400", "500", "700"],
  variable: "roboto_mono"
})
const IBM_Plex_Sans_init = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "IBM_Plex_Sans"
})



export const metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto_mono_init.variable} ${IBM_Plex_Sans_init.variable}`}>
        {children}
      </body>
    </html>
  );
}
